#! /bin/sh
set -euvx
perf record \
  -e branch-instructions          \
  -b                              \
  -o /var/cpuminer                \
  --                              \
  /usr/local/bin/cpuminer

